#version: '3.8'

services:
  writing:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: markpreview
    ports:
      - "17441:80"
    restart: unless-stopped
    # If you need to mount volumes for logs or additional files
    # volumes:
    #   - ./logs:/var/log/nginx
    #   - ./nginx.conf:/etc/nginx/conf.d/default.conf
    environment:
      - NGINX_HOST=localhost
      - NGINX_PORT=80
